version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: yaya_user
      POSTGRES_PASSWORD: yaya_password
      POSTGRES_DB: yaya_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data 

  app:
    build:
      context: .
    environment:
      DB_USER: yaya_user
      DB_PASSWORD: yaya_password
      DB_NAME: yaya_db
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
